name: Hello World

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo " Welcome to github action "
        
      - name: Print message
        run: echo " my first github action build "

      - name: Print message
        run: echo  " complete build "

      - name: Print message
        run: echo " Test build "

      - name: Print message
        run: echo " Build End "

    
